version: '3.8'

services:
  odoo:
    image: odoo:19.0
    container_name: odoo_app
    restart: always
    ports:
      - "8069:8069"
      - "8072:8072"
    environment:
      # --- CAPA DE BASE DE DATOS (AWS RDS) ---
      - HOST=odoo.cfiy5oksqwsu.us-east-1.rds.amazonaws.com
      - USER=odoo
      - PASSWORD=A123456b
      - PORT=5432
    volumes:
      # --- CAPA DE ALMACENAMIENTO COMPARTIDO (AWS EFS) ---
      # 1. Datos dinámicos: Sesiones de usuario, fotos y PDFs (filestore)
      - /mnt/efs/odoo_data:/var/lib/odoo
      
      # 2. Código: Módulos personalizados (como tu generador de PDF)
      - /mnt/efs/addons:/mnt/extra-addons

# No hay sección 'volumes:' abajo porque no usamos almacenamiento local de Docker
