apiVersion: v1
kind: Service
metadata:
  name: odoo-db
spec:
  ports:
  - port: 5432
  selector:
    app: odoo-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-db
spec:
  selector:
    matchLabels:
      app: odoo-db
  template:
    metadata:
      labels:
        app: odoo-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_USER
          value: "odoo"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: odoo-db-secret
              key: postgres-password
        - name: POSTGRES_DB
          value: "postgres"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-storage
        emptyDir: {} # Almacenamiento efímero
