apiVersion: v1
kind: Service
metadata:
  name: odoo-service
spec:
  type: LoadBalancer
  selector:
    app: odoo-web
  ports:
  - name: web
    port: 80
    targetPort: 8069
  - name: chat
    port: 8072
    targetPort: 8072
