apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo-web
  template:
    metadata:
      labels:
        app: odoo-web
    spec:
      # Odoo usa el UID 101, lo forzamos aquí también por seguridad
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      containers:
      - name: odoo
        image: odoo:latest
        ports:
        - containerPort: 8069
          name: odoo-http
        - containerPort: 8072
          name: odoo-chat
        env:
        - name: HOST
          value: "odoo-db"
        - name: USER
          value: "odoo"
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: odoo-db-secret
              key: postgresql-password
        volumeMounts:
        - name: efs-odoo-storage
          mountPath: /var/lib/odoo
          subPath: odoo-data
        - name: efs-odoo-storage
          mountPath: /etc/odoo
          subPath: config
        - name: efs-odoo-storage
          mountPath: /mnt/extra-addons
          subPath: addons
      volumes:
      - name: efs-odoo-storage
        persistentVolumeClaim:
          claimName: odoo-efs-pvc
